package testing;

import authentication.Authentication;
import users.*;
import appointments.Appointment;
import database_management.AppointmentService;
import database_management.DoctorService;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.Scanner;


// Basic text based UI generated by Chati to test the app
public class AppUI {

    private static final Scanner sc = new Scanner(System.in);

    public static void main(String[] args) throws Exception {
        System.out.println("=== Starting App ===");

        runAutoCompletionInitializer();   // <--- automatic background update

        while (true) {
            System.out.println("\n=== MAIN MENU ===");
            System.out.println("1) Login");
            System.out.println("2) Patient Signup");
            System.out.println("3) Doctor Signup");
            System.out.println("0) Exit");
            System.out.print("> ");

            switch (sc.nextLine()) {
                case "1" -> login();
                case "2" -> signupPatient();
                case "3" -> signupDoctor();
                case "0" -> { System.exit(0); }
                default -> System.out.println("Invalid option.");
            }
        }
    }


    // -------------------------------------------------------
    // LOGIN
    // -------------------------------------------------------
    private static void login() throws Exception {
        System.out.println("\n=== LOGIN ===");
        System.out.print("Email: ");
        String email = sc.nextLine();
        System.out.print("Password: ");
        String pwd = sc.nextLine();

        User user = Authentication.logIn(email, pwd);
        if (user == null) {
            System.out.println("Invalid credentials.");
            return;
        }

        if (user instanceof Patient p) patientMenu(p);
        else if (user instanceof Doctor d) doctorMenu(d);
    }


    // -------------------------------------------------------
    // SIGNUP
    // -------------------------------------------------------
    private static void signupPatient() throws Exception {
        System.out.println("\n=== PATIENT SIGNUP ===");
        System.out.print("Email: ");
        String email = sc.nextLine();
        System.out.print("First Name: ");
        String fn = sc.nextLine();
        System.out.print("Last Name: ");
        String ln = sc.nextLine();
        System.out.print("Password: ");
        String pwd = sc.nextLine();

        Patient p = Authentication.patientSignUp(email, fn, ln, pwd);
        if (p == null) {
            System.out.println("Signup failed, email already taken.");
        } else {
            System.out.println("Signup successful. Your ID = " + p.getId());
        }
    }

    private static void signupDoctor() throws Exception {
        System.out.println("\n=== DOCTOR SIGNUP ===");
        System.out.print("Email: ");
        String email = sc.nextLine();
        System.out.print("First Name: ");
        String fn = sc.nextLine();
        System.out.print("Last Name: ");
        String ln = sc.nextLine();
        System.out.print("Password: ");
        String pwd = sc.nextLine();
        System.out.print("Specialization: ");
        String spec = sc.nextLine();

        Doctor d = Authentication.doctorSignUp(email, fn, ln, pwd, spec);
        if (d == null) {
            System.out.println("Signup failed, email already taken.");
        } else {
            System.out.println("Signup successful. Your ID = " + d.getId());
        }
    }


    // -------------------------------------------------------
    // PATIENT MENU
    // -------------------------------------------------------
    private static void patientMenu(Patient p) throws Exception {
        while (true) {
            System.out.println("\n=== PATIENT MENU ===");
            System.out.println("Welcome, " + p.getName());
            System.out.println("1) My Appointments");
            System.out.println("2) Book Appointment (by ID)");
            System.out.println("3) Cancel Appointment");
            System.out.println("0) Logout");
            System.out.print("> ");

            switch (sc.nextLine()) {
                case "1" -> viewAppointments(p.getMyAppointments());
                case "2" -> {
                    System.out.print("Enter appointment ID to book: ");
                    int id = Integer.parseInt(sc.nextLine());
                    System.out.println(p.bookAppointment(id) ? "Booked." : "Failed.");
                }
                case "3" -> {
                    System.out.print("Enter appointment ID to cancel: ");
                    int id = Integer.parseInt(sc.nextLine());
                    System.out.println(p.cancelAppointment(id) ? "Canceled." : "Failed.");
                }
                case "0" -> { return; }
                default -> System.out.println("Invalid.");
            }
        }
    }


    // -------------------------------------------------------
    // DOCTOR MENU
    // -------------------------------------------------------
    private static void doctorMenu(Doctor d) throws Exception {
        while (true) {
            System.out.println("\n=== DOCTOR MENU ===");
            System.out.println("Welcome, Dr. " + d.getLastName());
            System.out.println("1) My Appointments");
            System.out.println("2) Create Available Slot");
            System.out.println("3) Mark Completed");
            System.out.println("4) Cancel Appointment");
            System.out.println("0) Logout");
            System.out.print("> ");

            switch (sc.nextLine()) {
                case "1" -> viewAppointments(d.getMyAppointments());
                case "2" -> createSlot(d);
                case "3" -> {
                    System.out.print("Enter appointment ID: ");
                    int id = Integer.parseInt(sc.nextLine());
                    System.out.println(d.completeAppointment(id) ? "Completed." : "Failed.");
                }
                case "4" -> {
                    System.out.print("Enter appointment ID: ");
                    int id = Integer.parseInt(sc.nextLine());
                    System.out.println(d.cancelAppointment(id) ? "Canceled." : "Failed.");
                }
                case "0" -> { return; }
                default -> System.out.println("Invalid.");
            }
        }
    }


    // -------------------------------------------------------
    // CREATE SLOT (Doctor)
    // -------------------------------------------------------
    private static void createSlot(Doctor d) throws Exception {
        System.out.print("Enter date-time (yyyy-MM-ddTHH:mm): ");
        String raw = sc.nextLine();
        LocalDateTime dt = LocalDateTime.parse(raw);

        System.out.print("Notes: ");
        String notes = sc.nextLine();

        DoctorService.createAvailableSlot(d.getId(), dt, notes);
        System.out.println("Slot created.");
    }


    // -------------------------------------------------------
    // DISPLAY APPOINTMENTS
    // -------------------------------------------------------
    private static void viewAppointments(List<Appointment> list) {
        if (list.isEmpty()) {
            System.out.println("No appointments.");
            return;
        }

        System.out.println("\n--- APPOINTMENTS ---");
        for (Appointment a : list) {
            System.out.println(
                    "ID=" + a.getId() +
                            " | Doctor = " + a.getDoctor().getName() +
                            " | Patient = " + (a.getPatient() == null ? "—" : a.getPatient().getName()) +
                            " | " + a.getDate() +
                            " | " + a.getStatus()
            );
        }
    }


    // -------------------------------------------------------
    // AUTO-COMPLETION INITIALIZER
    // -------------------------------------------------------
    private static void runAutoCompletionInitializer() throws Exception {
        System.out.println("Running auto-completion check...");

        Map<String, Object> filters = new HashMap<>();
        filters.put("status", "eq.SCHEDULED");

        List<Appointment> list = AppointmentService.fetchAppointments(filters);

        LocalDateTime now = LocalDateTime.now();

        for (Appointment a : list) {
            LocalDateTime limit = now.minusDays(1).minusHours(8);
            if (a.getDate().isBefore(limit)) {
                a.setStatus("COMPLETED");
                AppointmentService.updateAppointment(a);
                System.out.println("Auto-completed appointment ID " + a.getId());
            }
        }
        System.out.println("Auto-completion done.");
    }
}

